CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS attempts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  flag VARCHAR(255) NOT NULL,
  guessed_country VARCHAR(100) NOT NULL,
  is_correct BOOLEAN NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS flags (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  country VARCHAR(100) NOT NULL UNIQUE,
  image_url VARCHAR(255) NOT NULL
);
